config/routes.rb
Rails.application.routes.draw do
  namespace :guide do
    get 'bookings/index'
  end
  get 'bookings/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :guides, only: [:index, :show, :new, :create ] do
    resources :bookings, only: :create
  end

  namespace :guide do
    resources :bookings, only: :index, as: :guide_bookings
  end


  resources :bookings, only: [:index, :update]



  # # DETAILED ROUTES

  # # User Story 1
  # root to: 'pages#home'

  # # User Stories 2
  # get '/search', to: 'guides#search', as: :search_guides

  # # User Story 3
  # get '/guides/:id', to: 'guides#show', as: :guide

  # # User Story 4 - DON'T USE

  # # User Story 5
  # post '/guides/:guide_id/bookings', to: 'bookings#create'

  # # User Story 6
  # get '/bookings', to: 'bookings#index', as: :bookings

  # # User Story 7 - QUESTION - what is the correct syntax for guide/bookings controller?
  # get '/guide/bookings', to: 'guide/bookings#index', as: :guide_bookings

  # # User Story 8  - DON'T USE
  # # User Story 9  - DON'T USE

  # # User Story 10
  # get 'guides/new', to: 'guides#new', as: :new_guide

  # # User Story 11
  # post 'guides', to: 'guides#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # STATUSES = ['Pending', 'Accepted', 'Rejected']
  belongs_to :user
  delegate :name, :to => :user, :prefix => true
  belongs_to :guide
  delegate :title, :location, :description, :to => :guide, :prefix => true
  validates :date, presence: true
  # validates :status, inclusion: { in: STATUSES }
  attribute :status, :string, default: 'Pending'
end

app/models/guide.rb
class Guide < ApplicationRecord
  CATEGORIES = ['History', 'Nature', 'Culture', 'Art', 'Sports', 'Music', 'Food and Drinks', 'Outdoors', 'Shopping', 'Festivals', 'Relaxation', 'Action and Adventure', 'Touristy', 'Family friendly', 'Great for groups']
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: true
  # validates :date, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  include PgSearch::Model
  pg_search_scope :search_by_title_location_description_and_price,
    against: [ :title, :location, :description, :price ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable
  has_many :bookings
  has_many :guides, dependent: :destroy
  has_many :bookings_as_guide, through: :guides, source: :bookings
  validates :name, presence: true

  # omniauth
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        # email:    User.dummy_email(auth),
        # password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).all
    @guides = current_user.guides
  end

  def create
    @guide = Guide.find(params[:guide_id])
    @booking = Booking.new(booking_params)
    @booking.guide = @guide
    @booking.user = current_user
    authorize @guide
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    # redirect_to booking_path(@booking)
    # else
    #   render :index
    end
  end

  def update
    @booking = Booking.find(params[:id])
    # @guide = Guide.find(params[:guide_id])
    authorize @booking
    # authorize @guide
    if @booking.update(booking_params)
      redirect_to bookings_path
    # else
    #   render :edit
    end
  end

  private

  def booking_params
   params.require(:booking).permit(:status, :date, :duration, :guide_id)
  end
end

app/controllers/guide/bookings_controller.rb
class Guide::BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  # def edit
  # # pending to accepted
  # # rejected
  # end



  # private

  # def booking_params
  #  params.require(:booking).permit(:status, :date, :duration, :guide_id)
  #   # pass status and user_id in permit()?
  # end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @booking = Booking.new
    # @guides = policy_scope(Guide).order(id: :asc)
    if params[:query].present?
      @guides = policy_scope(Guide).search_by_title_location_description_and_price(params[:query])
    else
      @guides = policy_scope(Guide.all)
    end
  end

  def show
    @guide = Guide.find(params[:id])
    authorize @guide
  end

  def new
    @guide = Guide.new
    authorize @guide
  end

  def create
    @guide = Guide.new(guide_params)
    @guide.user = current_user
    authorize @guide
    if @guide.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @guide = Guide.find(params[:id])
    authorize @guide
    if @guide.update(guide_params)
      redirect_to guide_path(@guide)
    else
      render :edit
    end
  end

  private

  def guide_params
    params.require(:guide).permit(:location, :title, :date, :category, :description, :price, :photo) # :user_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  def github
    callback_from :github
  end

  def linkedin
    callback_from :linkedin
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<nav class="jimotrip-navbar p-1">
	<div class="flexbox align-items-center">
	  <div class="flexbox align-items-center">
 	    <%= link_to 'Jimotrip', root_path, class: "jimotrip-font-color jimo-logo-font ml-3 hover-color" %>
 	    <h4 class="p-3 mt-3 jimotrip-font-color">Explore with a local, enjoy like the locals!</h4>
	  </div>
		  <div class="flexbox nav-right">
 	      <%= link_to 'Create a Jimotrip', new_guide_path(@user), class: "jimotrip-font-color nav-right header-link hover-color" %>
 	      <%= link_to "My Jimotrips", bookings_path(@user),  class: "jimotrip-font-color nav-right header-link hover-color px-3" %>
<!-- 		  	<a class="px-3 navbar-brand jimotrip-font-color hover-color" href="#">My Jimotrips</a>
 -->		  	<a class="navbar-brand jimotrip-font-color lang-text hover-color" href="#"><i class="fas fa-flag-usa"></i></a>
		  	<img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
		  </div>
	  </div>
	</div>
</nav>

<div class="container mt-3">
	<div class="d-flex">

<!-- Filer by container -->

  	<div class="dashboard-column col-3 mr-3">
  		<h4 class="salmon-text text-center p-3"><strong>Filter by:</strong></h4>
  		<ul class="dark-grey-text no-bullets">
  			<li><i class="far fa-square"></i>  Booking Status</li>
  			<li><i class="far fa-square"></i>  City</li>
  			<li><i class="far fa-square"></i>  Category</li>
  		</ul>
  	</div>

<!-- container for both dashboards -->

  	<div class="dashboard-main col-9 p-0">

			<ul class="nav nav-pills nav-fill mb-3" id="pills-tab" role="tablist">
			  <li class="nav-item">
			    <a class="nav-link active nav-link-dark" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Jimotrips to Experience</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link nav-link-dark" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Jimotrips I've Created</a>
			  </li>
			</ul>

<!-- dashboard container -->
<%# raise %>
			<div class="tab-content" id="pills-tabContent">

        <!-- dashboard Jimotrips to Experience -->

			  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
			  	<div class="d-flex flex-wrap justify-content-around">
					<%# raise %>
					<% @bookings.each do |booking| %>
				  <div class="tab-card m-3 card-style-new">
						<% if booking.guide.photo.attached? %>
							<%= cl_image_tag booking.guide.photo.key, alt: "a photo uploaded by the user" %>
						<% else %>
							<!-- <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945213/authentic_expriences_bgq73f.jpg" > -->
							<%= image_tag "Grass.jpg", alt: "alttext" %>
						<% end %>

						  <div class="tab-card-infos">
						    <div>

				<!-- 		    <div class="d-flex justify-content-between">
						    	<div> -->
							      <p class="title-font"><%= booking.guide_title %></p>
							      <p class="dark-grey-text location-font">Location: <%= booking.guide_location %></p>
							      <p class="dark-grey-text description-font"><%= booking.guide_description %></p>
							      <% if  booking.status == "Pending" %>
		                  <p class="text-white badge badge-pill badge-warning"><%= booking.status %></p>
							      <% elsif booking.status == "Accepted" %>
		                  <p class="text-white badge badge-pill badge-success"><%= booking.status %></p>
							      <% else %>
		                  <p class="text-white badge badge-pill badge-danger"><%= booking.status %></p>
							      <% end %>
<!-- 									</div>
									<div class="nav-right"> -->
<!-- 	                  <img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
	                  <p class="dark-grey-text"><%#= User.find(booking.id).name %></p> -->
	<!-- 					    	</div>
						    </div> -->

						    </div>
						  </div>
						</div>
						<% end %>
			  	</div>
			  </div>

        <!-- dashboard Jimotrips I've Created -->

			  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
			  	<div class="d-flex  flex-wrap justify-content-around">
					<% @guides.each do |guide| %>
				  <div class="tab-card m-3">
				  					  <div class="tab-card m-3 card-style-new">
						<% if guide.photo.attached? %>
							<%= cl_image_tag guide.photo.key, alt: "a photo uploaded by the user" %>
						<% else %>
							<!-- <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945213/authentic_expriences_bgq73f.jpg" > -->
							<%= image_tag "Grass.jpg", alt: "alttext" %>
						<% end %>
						<!-- <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945213/authentic_expriences_bgq73f.jpg" > -->
						  <div class="tab-card-infos">
						    <div>
						      <p class="title-font"><%= guide.title %></p>
						      <p class="dark-grey-text location-font"><%= guide.location %></p>
						      <p class="dark-grey-text description-font"><%= guide.description %></p>

                  <% guide.bookings.each do |booking| %>
                    <p class="dark-grey-text description-font">Booked by <%= booking.user_name %></p>

                    <% if  booking.status == "Pending" %>
		                  <p class="text-white badge badge-pill badge-warning"><%= booking.status %></p>
							      <% elsif booking.status == "Accepted" %>
		                  <p class="text-white badge badge-pill badge-success"><%= booking.status %></p>
							      <% else %>
		                  <p class="text-white badge badge-pill badge-danger"><%= booking.status %></p>
							      <% end %>

                    <!-- <p class="dark-grey-text description-font"><strong><%#= booking.status %></strong></p> -->
  						      <!-- <p class="dark-grey-text">Don't just observe the culture. Live it.</p> -->



                </div>
						  </div>
  						      <div class="d-flex justify-content-center mb-3">
  						      <%= simple_form_for booking do |f| %>
                      <%= f.input :status, input_html: { value: "Accepted" }, as: :hidden %>
                      <%= f.submit "Accept", class: "mr-0 mx-3 btn btn-outline-success" %>
                    <% end %>
                    <%= simple_form_for booking do |f| %>
                      <%= f.input :status, input_html: { value: "Rejected" }, as: :hidden %>
                      <%= f.submit "Reject", class: "mx-3 btn btn-outline-danger" %>
                    <% end %>
                  <% end %>
  						      </div>
						</div>
						<% end %>
			  	</div>
			  </div>

			</div>
  	</div>
  </div>
</div>

app/views/guides/index.html.erb
<nav class="jimotrip-navbar p-1">
  <div class="flexbox align-items-center">
    <div class="flexbox align-items-center">
      <%= link_to 'Jimotrip', root_path, class: "jimotrip-font-color jimo-logo-font ml-3 hover-color" %>
      <h4 class="p-3 mt-3 jimotrip-font-color">Explore with a local, enjoy like the locals!</h4>
    </div>
      <div class="flexbox nav-right">
        <%= link_to 'Create a Jimotrip', new_guide_path(@user), class: "jimotrip-font-color nav-right header-link hover-color" %>
        <%= link_to "My Jimotrips", bookings_path(@user),  class: "jimotrip-font-color nav-right header-link hover-color px-3" %>
<!--        <a class="px-3 navbar-brand jimotrip-font-color hover-color" href="#">My Jimotrips</a>
 -->        <a class="navbar-brand jimotrip-font-color lang-text hover-color" href="#"><i class="fas fa-flag-usa"></i></a>
        <img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
      </div>
    </div>
  </div>
</nav>

<div class="m-3">
  <h1>Experiences in Tokyo</h1>
  <!-- <p> COUNT experiences for DATE</p> -->
</div>

<div class="cards-guides-grid">
<%# raise %>
  <% @guides.each do |guide| %>

      <div class="card-guide">
<!--         <img src="https://archive.dannychoo.com/uploads/imported-images/2010/02/25412/e17ffadf1ec1b2c3eff4c02d69badcef.jpg"/>
 -->        <% if guide.photo.attached? %>
              <%= cl_image_tag guide.photo.key, alt: "a photo uploaded by the user" %>
            <% else %>
              <!-- <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945213/authentic_expriences_bgq73f.jpg" > -->
              <%= image_tag "Grass.jpg", alt: "alttext" %>
            <% end %>

        <div class="card-guide-infos">
          <div class>
            <h2 class="card-guide-title title-type"><%= guide.title %></h2>
            <p class= "card-guide-location location-type mt-2"><%= guide.location %></p>
            <p class="card-guide-price price-type mt-1">¥<%= guide.price %> /day /person</p>
            <p class= "card-guide-location description-type mt-3"><%= guide.description %></p>
          </div>
          <div>
           <img src="https://avatars0.githubusercontent.com/u/10365357?v=4" class="card-guide-user avatar-card-guide-bordered" />
            <!-- <i class="fas fa-torii-gate"></i> -->
          </div>
        </div>
        <div class="button-book-now m-0">
          <!-- the book now button should link to the bookings dashboard -->
          <%= simple_form_for [guide, @booking] do |f| %>
          <!-- add flatpickr to date (enable time) -->
          <%#= f.input :date, input_html: {class: "datepicker"} %>
          <%= f.input :date, html5: true, label: false %>
          <%= f.submit "Book now", class: "btn btn-salmon text-white" %>
          <% end %>
        </div>
      </div>
  <% end %>

</div>

app/views/guides/show.html.erb
<!-- navbar -->


<nav class="jimotrip-navbar p-1">
  <div class="flexbox align-items-center">
    <div class="flexbox align-items-center">
      <%= link_to 'Jimotrip', root_path, class: "jimotrip-font-color jimo-logo-font ml-3 hover-color" %>
      <h4 class="p-3 mt-3 jimotrip-font-color">Explore with a local, enjoy like the locals!</h4>
    </div>
      <div class="flexbox nav-right">
        <%= link_to 'Create a Jimotrip', new_guide_path(@user), class: "jimotrip-font-color nav-right header-link hover-color" %>
        <%= link_to "My Jimotrips", bookings_path(@user),  class: "jimotrip-font-color nav-right header-link hover-color px-3" %>
<!--        <a class="px-3 navbar-brand jimotrip-font-color hover-color" href="#">My Jimotrips</a>
 -->        <a class="navbar-brand jimotrip-font-color lang-text hover-color" href="#"><i class="fas fa-flag-usa"></i></a>
        <img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
      </div>
    </div>
  </div>
</nav>


<!-- congratulations message -->
<div class="text-center dark-grey-text">
  <h1 class="dark-grey-text">Congratulations <%= @current_user.name %>!</h1>
  <p>Your new Jimotrip has been created</p>
  <p>You can review your Jimotrip card below</p>
</div>

<!-- guide card -->

<div class="container dark-grey-text">
  <div class="row justify-content-center mt-5">

    <div class="col-12 col-lg-6">
    <%#= cl_image_tag @guide.photo.key, height: 300, width: 400, crop: :fill %>
    <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589947500/high-angle-photo-of-robot-2599244_u421n4.jpg" style="width: 540px"/>

      <div class="card-guide">
        <div class="d-flex p-3 justify-content-between" style="height: 200px">
          <div>
            <h2><%#= @guide.name %></h2>
            <h4 class=""><strong></strong>Soccer & Izakaya... with Japanese Robots</strong></h4>
            <h5 class=""><%= @guide.location %></h5>
            <br>
            <h6 class="">Enjoy a true Japanese experience! Play soccer, then enjoy a Japanese beer at a Japanese izakaya with me and Japanese robots!</h6>
            <br>
           <h2 class="card-guide-pricing"><%= @guide.price %> Yen</h2>
          </div>
          <div>
            <img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
            <h2 class="salmon-text"><%= @current_user.name %></h2>
          </div>
          <!-- <div>
          <%# simple form  %>
            <%# simple_form_for (@guide) do |f| %>
              <%# f.input :date, html5: true %>
              <%# f.input :status %>
              <%# f.submit class: "btn btn-salmon hover-color text-white", value: "become a Jimotrip guide" %>
            <%# end %>
           <%# link_to 'Booking', guide_bookings_path(@guide), method: :post %>
          </div> -->
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jimotrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- navbar -->

<nav class="jimotrip-navbar p-1">
	<div class="flexbox align-items-center">
	  <div class="flexbox align-items-center">
 	    <%= link_to 'Jimotrip', root_path, class: "jimotrip-font-color jimo-logo-font ml-3 hover-color" %>
 	    <h4 class="p-3 mt-3 jimotrip-font-color">Explore with a local, enjoy like the locals!</h4>
	  </div>
		  <div class="flexbox nav-right">
 	      <%= link_to 'Create a Jimotrip', new_guide_path(@user), class: "jimotrip-font-color nav-right header-link hover-color" %>
 	      <%= link_to "My Jimotrips", bookings_path(@user),  class: "jimotrip-font-color nav-right header-link hover-color px-3" %>
<!-- 		  	<a class="px-3 navbar-brand jimotrip-font-color hover-color" href="#">My Jimotrips</a>
 -->		  	<a class="navbar-brand jimotrip-font-color lang-text hover-color" href="#"><i class="fas fa-flag-usa"></i></a>
		  	<img class="avatar" alt="avatar" src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589894499/uif0jtkw7bylokixyni6y7nhzamm.jpg" />
		  </div>
	  </div>
	</div>
</nav>


<!-- banner -->

<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Explore with a local, enjoy like the locals!</h1>
    <p>Live a unique, culturally immersive and unforgettable life experience</p>
  </div>
</div> -->


<!-- search  -->

<div class="container mt-5 mb-5">

	<h1 class="text-center home-text">Discover new <strong>Jimotrip</strong> experiences</h1>
  <%# simple_form_for :search, url: root_path, method: :get do |f| %>
  <%= form_tag guides_path, method: :get do %>
  <!-- <div class="search-form-control form-group"> -->
  	<div class="d-flex">
	    <%= text_field_tag :query,
	    params[:query],
	    class: "form-control",
	    placeholder: "Find your next Jimotrip!"
	    %>
	    <%= submit_tag "Search", class: "btn btn-salmon text-white px-5" %>
    </div>
    <!-- <input class="form-control string required dark-grey-text" type="text" name="search[query]" id="search_query" value="search for a Jimotrip by city, date, activity, or interest"/>
    <button name="button" type="submit" class="btn btn-jimo text-white">
      <i class="fas fa-search"></i> search
    </button> -->
  <% end %>


<!-- guide cards -->


	<div class="flexbox justify-content-around mt-5">
		<div class="card-homepage mr-3">

		  <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945174/meet_locals_krzfen.jpg" >
		  <div class="card-homepage-infos">
		    <div>
		      <h2 class="salmon-text">Meet locals.</h2>
		      <p class="dark-grey">Befriend locals on your next experience.</p>
		    </div>
		  </div>
		</div>

		<div class="card-homepage">

		  <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945213/authentic_expriences_bgq73f.jpg" >
		  <div class="card-homepage-infos">
		    <div>
		      <h2 class="salmon-text">Authentic experiences.</h2>
		      <p class="dark-grey-text">Don't just observe the culture. Live it.</p>
		    </div>
		  </div>
		</div>

		<div class="card-homepage ml-3">

		  <img src="https://res.cloudinary.com/dwd42pppi/image/upload/v1589945182/new_adventures_j84rk3.jpg" >
		  <div class="card-homepage-infos">
		    <div>
		      <h2 class="salmon-text">New adventures.</h2>
		      <p class="dark-grey">Where will your next Jimotrip take you?</p>
		    </div>
		  </div>
		</div>

	</div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>